### PR TITLE
refactor(core): Reduce code duplication in polling monitors

### PR DESCRIPTION
**Pull request by wheleph**
This PR fixes https://github.com/spinnaker/spinnaker/issues/2166.

The basic idea is to reduce the code duplication by using [template method design pattern](https://en.wikipedia.org/wiki/Template_method_pattern). All the common code is pushed to `CommonPollingMonitor`.

### CODE REVIEW

**Comment by jeyrschabu** [comment]
Looks good. One comment I have is that we prefer Java for new classes.

**Comment by wheleph** [comment]
I see. I guess it means that I need to reimplement the whole hierarchy of build monitors in Java since it will be a bit confusing to have the parent class in Java and the rest in Groovy. It shouldn't be very hard and I'm going to work on this.

But I'm wondering why are you going away from Groovy?

Also I assume it doesn't mean that we need to re-implement the test in Java, right?

**Comment by jeyrschabu** [comment]
@wheleph it's a new pattern we are adopting (favor java over groovy for new classes). 

That's a good point in this situation with the child classes being of a different type. No need to convert the class

**Comment by wheleph** [comment]
If you're cool with leaving the code in Groovy then it's ok. Do you have any idea when the code will be merged into master so that I can continue with the next PR?

**Pull request merged**
