### PR TITLE
feat(gcb): Add support for cancelling GCB build

### PR DESCRIPTION
**Pull request by sharvanath**

### CODE REVIEW

**Comment by sharvanath** [comment]
@ezimanyi could you gelp take a look?

**Comment by mattgogerly** [comment]
Are there any tests you can add for this?

**Comment by sharvanath** [comment]
> Are there any tests you can add for this?

@mattgogerly All the changes I made are in igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/ I do not see any test coverage for this.

**Comment by mattgogerly** [comment]
> > Are there any tests you can add for this?
> 
> @mattgogerly All the changes I made are in igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/ I do not see any test coverage for this.

The existing tests are in the groovy directory

**Comment by sharvanath** [comment]
> > > Are there any tests you can add for this?
> > 
> > 
> > @mattgogerly All the changes I made are in igor-web/src/main/java/com/netflix/spinnaker/igor/gcb/ I do not see any test coverage for this.
> 
> The existing tests are in the groovy directory

Added a test.

**Comment by sharvanath** [comment]
@mattgogerly ping on this!

**Comment by mattgogerly** [comment]
Sorry for the delay

@Mergify-io update

**Comment by mattgogerly** [comment]
Sorry for the delay

@Mergifyio update

**Review by mattgogerly — APPROVED** [review]

**Comment by sharva-scio** [comment]
> Sorry for the delay
> 
> @Mergifyio update

np, thanks for reviewing it.

**Comment by sharvanath** [comment]
> Sorry for the delay
> 
> @Mergifyio update

Np, thanks for reviewing it

**Pull request merged**
