### PR TITLE
fix(ArtifactoryPollingMonitor): Fix failing validation on lockName

### PR DESCRIPTION
**Pull request by sirigithub**
This fix addresses a validation failure in kork when a polling agent tries to acquire a lock using the lockService. This issue can be reproduced by enabling Artifactory build trigger for maven artifacts. The search configuration looks like 

```
searches:
      - name: test-maven
        permissions: {}
        baseUrl: https://artifactory-url/artifactory
        repo: test-maven-local
        groupId: com.mycompany
        username:
```
The Artifactory polling logic fails with the following exception:
```
Caused by: com.netflix.spinnaker.kork.exceptions.ConstraintViolationException: Lock name must be alphanumeric, may contain dots
	at com.netflix.spinnaker.kork.lock.LockManager$LockOptions.validateInputs(LockManager.java:315
```
The class CommonPollingMonitor initialises the lockName variable as
```
final String lockName = format("%s.%s", getName(), ctx.partitionName);
```
which in this case will be
```
 artifactoryPublishingMonitor.https://artifactory-url/artifactory/test-maven-local
```
The issue can be fixed by validating if the lockName passed from CommonPollingMonitor.java passes the regex validation  ^[a-zA-Z0-9.-] and replacing any unacceptable characters.

Referenced issue : https://github.com/spinnaker/spinnaker/issues/5186

### CODE REVIEW

**Comment by sirigithub** [comment]
Results after enabling fix:

```
[RxIoScheduler-4] c.n.s.kork.jedis.lock.RedisLockManager   : Acquired Lock Lock{name='artifactoryPublishingMonitor.httpsartifactory-urltest-maven-local', ownerName='spin-igor-7fc86bcb98-qh7jq', leaseDurationMillis=30000, successIntervalMillis=0, failureIntervalMillis=0, version=1575328441804, ownerSystemTimestamp=1575328441804, attributes=''}.

[RxIoScheduler-4] c.n.s.kork.jedis.lock.RedisLockManager   : Lock Lock{name='artifactoryPublishingMonitor.httpsartifactory-urltest-maven-local', ownerName='spin-igor-7fc86bcb98-qh7jq', leaseDurationMillis=30000, successIntervalMillis=0, failureIntervalMillis=0, version=1575328441804, ownerSystemTimestamp=1575328441804, attributes=''} will heartbeats for 30000ms
[RxIoScheduler-4] c.n.s.kork.jedis.lock.RedisLockManager   : Released lock (wasWorkSuccessful: true, Lock{name='artifactoryPublishingMonitor.httpsartifactory-urltest-maven-local', ownerName='spin-igor-7fc86bcb98-qh7jq', leaseDurationMillis=30000, successIntervalMillis=0, failureIntervalMillis=0, version=1575328441804, ownerSystemTimestamp=1575328441804, attributes=''})
 

```

**Comment by robzienert** [comment]
Would like to see a test written to assert this behavior.

**Comment by sirigithub** [comment]
> Would like to see a test written to assert this behavior.

Thanks Rob, I will add a test for the ArtifactoryMonitorSpec.

**Comment by sirigithub** [comment]
@robzienert Included a test that uses the LockService and hence calls the pollSingle method in CommonPollingMonitor. 

This will assert the regex validation.

**Pull request merged**
