### PR TITLE
fix(concourse): update auth for v6.5+

### PR DESCRIPTION
**Pull request by jaredstehler**
another concourse minor release has broken token authentication (this is a private API, so I expect this to continue to occur until they expose a public one).

see: https://github.com/concourse/concourse/pull/5897

### CODE REVIEW

**Comment by PFacheris** [comment]
Any updates here? Would be awesome to get this fixed as we've recently been trying out the Concourse integration (which has been really great 😄) and our most recent upgrade broke that.

**Review by gal-yardeni — APPROVED** [review]
lgtm. Please rebase so we can merge it. thanks!

**Comment by gal-yardeni** [comment]
@jaredstehler it needs another rebasing :( unfortunately, I can't do it for you..

**Comment by jaredstehler** [comment]
no worries, all set!

**Pull request merged**
