### PR TITLE
Handle "." in request parameter

### PR DESCRIPTION
**Pull request by jeyrschabu**
- Updated to use masters/{name:.+} to handle names like jenkins.net

### CODE REVIEW

**Comment by jeyrschabu** [comment]
@ajordens PTAL . This takes care of https://github.com/spinnaker/spinnaker/issues/1165

**Comment by ajordens** [comment]
I don't think it's actually necessary in all these spots, only the ones where the `{master}` would be the last element in the path?

**Comment by jeyrschabu** [comment]
You are right. Did a quick test, only necessary for the last element (or potential last element) . 
This is now updated

**Comment by ajordens** [comment]
LGTM

**Pull request merged**
