### PR TITLE
feat(jenkins): Support for overriding TrustStore used by Jenkins clients

### PR DESCRIPTION
**Pull request by ajordens**
```
jenkins:
  masters:
    -
      address: "https://jenkins.com"
      name: spinnaker
      trustStore: "*"
```

or:

```
jenkins:
  masters:
    -
      address: "https://jenkins.com"
      name: spinnaker
      trustStore: /path/to/truststore.p12
      trustStoreType: PKCS12
      trustStorePassword: my_truststore_password
```

### CODE REVIEW

**Comment by sergedonaldp** [comment]
Hi @ajordens  I am trying the trust-store override in 1.13 and I get this error: `ERROR Could not translate your halconfig: Unrecognized field

  "trustStore" (class

  com.netflix.spinnaker.halyard.config.model.v1.ci.jenkins.JenkinsMaster), not

  marked as ignorable (5 known properties: "name", "address", "username",

  "password", "csrf"])

at [Source: UNKNOWN; line: -1, column: -1] (through reference chain:

  com.netflix.spinnaker.halyard.config.model.v1.node.Halconfig["deploymentConfigurations"]->java.util.ArrayList[1]->com.netflix.spinnaker.halyard.config.model.v1.node.DeploymentConfiguration["ci"]->com.netflix.spinnaker.halyard.config.model.v1.node.Cis["jenkins"]->com.netflix.spinnaker.halyard.config.model.v1.ci.jenkins.JenkinsCi["masters"]->java.util.ArrayList[0]->com.netflix.spinnaker.halyard.config.model.v1.ci.jenkins.JenkinsMaster["trustStore"])


`

**Comment by sergedonaldp** [comment]
Hi @ajordens I am still not able to trigger a pipeline when a jenkins job is successful. 
Despite upgrading to 1.13 and having the settings in place for the truststore: 
`Caused by: retrofit.RetrofitError: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at retrofit.RetrofitError.networkError(RetrofitError.java:27) ~[retrofit-1.9.0.jar:na]
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395) ~[retrofit-1.9.0.jar:na]
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240) ~[retrofit-1.9.0.jar:na]
	at com.sun.proxy.$Proxy92.getProjects(Unknown Source) ~[na:na]
	at sun.reflect.GeneratedMethodAccessor151.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_201]
	at com.netflix.spinnaker.kork.telemetry.InstrumentedProxy.invoke(InstrumentedProxy.java:87) ~[kork-telemetry-3.9.2.jar:3.9.2]
	at com.sun.proxy.$Proxy92.getProjects(Unknown Source) ~[na:na]
	at com.netflix.spinnaker.hystrix.SimpleJava8HystrixCommand.run(SimpleJava8HystrixCommand.java:48) ~[kork-hystrix-3.9.2.jar:3.9.2]
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:294) ~[hystrix-core-1.4.21.jar:1.4.21]
	... 22 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

**Comment by sergedonaldp** [comment]
hi @ezimanyi , quick question regarding the issue with jenkins ssl. It does not seem to work in spinnaker v1.13.6 with Halyard v 1.19.2 despite the fix we pushed a couple of months ago. Can you help ?

**Comment by ezimanyi** [comment]
@sergedonaldp : I haven't used the custom TrustStore for Jenkins myself.  Do you think the issue is in Halyard generating the config, or in the actual igor code itself?  Can you get this to work when you configure directly?

**Comment by sergedonaldp** [comment]
Hi @ezimanyi thanks for your feedback. After investigating, it seems the issue is in the igor code itself. Even though halyard generates the right config, Igor is not picking up the trust store. I have also tried configuring directly and it is not working. I will take a look at the logic in Igor sometimes next week and will update the thread with more details.

**Pull request merged**
