### PR TITLE
feat(authz): Add ability to specify Google service account credential…

### PR DESCRIPTION
**Pull request by ttomsu**
… or raw OAuth bearer token to Jenkins master request.

I'm not 100% sure this will actually work as expected. Most Jenkins masters with username/password protection (including the one I tested with) require the `Basic` header, so any Oauth-guarded proxy will also require the ability to discern multiple values in the `Authorization header`. 

According to https://stackoverflow.com/a/38515091/5569046, this should work by RFC spec, but may not actually work in the wild. (cc @katrielt )

### CODE REVIEW

**Comment by duftler** [comment]
LGTM.
Would like @tomaslin to weigh in as well.

**Comment by skim1420** [comment]
@tomaslin ping thx

**Comment by ttomsu** [comment]
@tomaslin Anything to add here? If not I'll merge.

**Comment by robzienert** [comment]
@tomaslin ping - last chance

**Pull request merged**
